project_id = "ezewikxdukboalcybrfs"

[functions.secullum]
verify_jwt = false

[functions.endomarketing-agent]
verify_jwt = false

[functions.onboarding-agent]
verify_jwt = false

[functions.generate-trilha]
verify_jwt = false

[functions.banco-horas-agent]
verify_jwt = false

[functions.send-recruitment-email]
verify_jwt = false

[functions.sector-agent]
verify_jwt = false

[functions.holdprint-sync]
verify_jwt = false